# Generated by Django 2.1 on 2018-11-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(choices=[('Al Asimah', 'Al Asimah'), ('Hawalli', 'Hawalli'), ('Mubarak Al-Kabeer', 'Mubarak Al-Kabeer'), ('Al-Ahmadi', 'Al-Ahmadi'), ('Farwaniya', 'Farwaniya'), ('Al-Jahra', 'Al-Jahra')], default=0, max_length=20)),
                ('area', models.CharField(max_length=120)),
                ('block', models.PositiveIntegerField(default=1)),
                ('street', models.CharField(max_length=120)),
                ('building_or_house', models.PositiveIntegerField(default=1)),
                ('floor', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('extra_directions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDERED', 'ORDERED'), ('PACKED', 'PACKED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED')], default=0, max_length=20)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.Address')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='api.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('img', models.ImageField(upload_to='')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('FOOD', 'FOOD'), ('DRINKS', 'DRINKS')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('number', models.CharField(max_length=8)),
                ('firstname', models.CharField(default=1, max_length=80)),
                ('lastname', models.CharField(default=1, max_length=80)),
                ('email', models.CharField(default=1, max_length=80)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='api.Product'),
        ),
    ]
