# Generated by Django 2.1 on 2018-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('DRINKS', 'DRINKS')], default=0, max_length=20),
        ),
    ]
