# Generated by Django 2.1 on 2018-12-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181205_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MOBILES', 'MOBILES'), ('TABLETS', 'TABLETS')], default=0, max_length=20),
        ),
    ]
