# Generated by Django 2.1 on 2018-11-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181121_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.TextField(),
        ),
    ]
