# Generated by Django 2.1 on 2018-11-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181121_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(choices=[('AA', 'Al Asimah'), ('H', 'Hawalli'), ('M', 'Mubarak Al-Kabeer'), ('A', 'Al-Ahmadi'), ('F', 'Farwaniya'), ('J', 'Al-Jahra')], default=0, max_length=1)),
                ('area', models.CharField(max_length=120)),
                ('block', models.PositiveIntegerField(default=1)),
                ('street', models.CharField(max_length=120)),
                ('building_or_house', models.PositiveIntegerField(default=1)),
                ('floor', models.PositiveIntegerField(default=0)),
                ('extra_directions', models.TextField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'ORDERED'), ('P', 'PACKED'), ('S', 'SHIPPED'), ('D', 'DELIVERED')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('F', 'FOOD'), ('D', 'DRINKS')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Address'),
        ),
    ]
