# Generated by Django 2.1 on 2018-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181125_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='extra_directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
