# Generated by Django 2.1 on 2018-11-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20181126_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='theemail',
        ),
        migrations.AlterField(
            model_name='address',
            name='governorate',
            field=models.CharField(choices=[('Al Asimah', 'Al Asimah'), ('Hawalli', 'Hawalli'), ('Mubarak Al-Kabeer', 'Mubarak Al-Kabeer'), ('Al-Ahmadi', 'Al-Ahmadi'), ('Farwaniya', 'Farwaniya'), ('Al-Jahra', 'Al-Jahra')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('PACKED', 'PACKED'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('DRINKS', 'DRINKS')], default=0, max_length=1),
        ),
    ]
